# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'KidsActivities' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for KidsActivities
  pod 'FirebaseAuth'
  pod 'Firebase/Firestore'

  target 'KidsActivitiesTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
